name: "CI: Java"

on:
  workflow_call:
    inputs:
      java_version:
        description: "Java Version"
        default: "17"
        required: false
        type: string
      gradle_version:
        description: "Gradle Version"
        default: "current" ## See here for more options: https://github.com/gradle/gradle-build-action#use-a-specific-gradle-version
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ inputs.gradle_version }}
          arguments: build