name: "CI: Python"

on:
  workflow_call:
    inputs:
      additional_pytest_options:
        description: "Additional flags to pass to pytest"
        default: ""
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Local Repository
        uses: actions/checkout@v3
      - name: Checkout Central Repository
        uses: actions/checkout@v3
        with:
          repository: "mlschuweiler/.github"
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'shared-workflows/'
          ref: 'main'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      - name: Test with pytest
        run: |
          if [ -f '.coveragerc' ]; then
            echo "[+] Using present .coveragerc configuration!"
          else
            echo "[+] Using default .coveragerc file from mlschuweiler/.github/.github/config/ project!"
            echo "[+] Check documentation if you would like to override this file with your own"
            cp shared-workflows/.github/config/python.default.coveragerc ${GITHUB_WORKSPACE}/.coveragerc
          fi
          if [ -f '.pytest' ]; then
            echo "[+] Using present pytest.ini configuration!"
          else
            echo "[+] Using default pytest.ini file from mlschuweiler/.github/.github/config/ project!"
            echo "[+] Check documentation if you would like to override this file with your own"
            cp shared-workflows/.github/config/python.default.pytest.ini ${GITHUB_WORKSPACE}/pytest.ini
          fi
          pytest --cov-config=.coveragerc ${{ inputs.additional_pytest_options }}
